# Generated by Django 5.1.4 on 2026-01-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_author_blogpost_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(blank=True, help_text="Author name (e.g., 'John Smith' or 'Listen Hear Team')", max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Legacy: Leave blank and use author_name instead', null=True, on_delete=models.deletion.SET_NULL, related_name='blog_posts', to='users.user'),
        ),
    ]
