# Generated by Django 5.2.8 on 2026-02-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_notified_at'),
        ('blog', '0003_blogpost_author_name'),
    ]

    operations = [
    ]
