# Generated by Django 5.2.8 on 2025-11-30 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_builder',
            field=models.BooleanField(
                default=False,
                help_text='Designates whether this user is a builder/contractor with property management access.'
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(
                max_length=200,
                blank=True,
                help_text='Builder/contractor company name'
            ),
        ),
    ]