# Generated by Django 5.2.8 on 2025-12-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_builder_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, help_text='State (2-letter abbreviation)', max_length=2, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, help_text='Street address for installations', max_length=300, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, help_text='ZIP code', max_length=10, verbose_name='ZIP Code'),
        ),
    ]
