# Generated by Django 5.2.8 on 2026-03-20 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='showroom_markup_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage markup applied to all showroom package prices for this builder (0 = no markup).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Showroom Markup %'),
        ),
    ]
