# Generated by Django 5.2.8 on 2025-11-30 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, help_text='Property name or identifier')),
                ('address', models.TextField(help_text='Full property address')),
                ('property_type', models.CharField(max_length=100, blank=True, help_text='e.g., Residential, Commercial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_request', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='properties',
                    to='quotes.quoterequest',
                    help_text='Original quote request that created this property'
                )),
                ('builders', models.ManyToManyField(
                    related_name='managed_properties',
                    to=settings.AUTH_USER_MODEL,
                    limit_choices_to={'is_builder': True},
                    help_text='Builders assigned to manage this property'
                )),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('package_description', models.TextField(blank=True)),
                ('price_snapshot', models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(
                    max_length=20,
                    choices=[
                        ('pending', 'Pending'),
                        ('date_requested', 'Date Requested'),
                        ('scheduled', 'Scheduled'),
                        ('in_progress', 'In Progress'),
                        ('completed', 'Completed'),
                        ('cancelled', 'Cancelled'),
                    ],
                    default='pending'
                )),
                ('requested_install_date', models.DateField(null=True, blank=True)),
                ('confirmed_install_date', models.DateField(null=True, blank=True)),
                ('completion_date', models.DateField(null=True, blank=True)),
                ('builder_notes', models.TextField(blank=True, help_text='Notes from builder')),
                ('company_notes', models.TextField(blank=True, help_text='Notes from company')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='packages',
                    to='products.property'
                )),
                ('package', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='products.package'
                )),
            ],
            options={
                'verbose_name': 'Purchased Package',
                'verbose_name_plural': 'Purchased Packages',
                'ordering': ['status', 'requested_install_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(
                    max_length=30,
                    choices=[
                        ('general', 'General Note'),
                        ('date_request', 'Date Request'),
                        ('date_confirmation', 'Date Confirmation'),
                        ('date_denial', 'Date Denial'),
                        ('status_change', 'Status Change'),
                    ]
                )),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL
                )),
                ('property', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='notes',
                    to='products.property'
                )),
                ('package', models.ForeignKey(
                    null=True,
                    blank=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='products.purchasedpackage',
                    help_text='Associated package if note is package-specific'
                )),
            ],
            options={
                'verbose_name': 'Property Note',
                'verbose_name_plural': 'Property Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]