# Generated by Django 5.2.8 on 2025-11-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_property_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertynote',
            name='property',
        ),
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertynote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='propertynote',
            name='package',
        ),
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='package',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyNote',
        ),
        migrations.DeleteModel(
            name='PurchasedPackage',
        ),
    ]
