# Generated by Django 5.2.8 on 2025-12-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_propertynote_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='installation_phase',
            field=models.CharField(choices=[('prewire', 'Wiring and Networking'), ('automation_lighting', 'Automation and Lighting'), ('audio_entertainment', 'Audio and Entertainment'), ('physical_programming', 'Physical Automation, Programming and Customization')], default='prewire', help_text='Installation phase for this package', max_length=50),
        ),
    ]
