# Generated by Django 5.2.8 on 2025-12-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_package_installation_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID or https://youtu.be/VIDEO_ID)'),
        ),
    ]
