# Generated by Django 5.2.8 on 2025-12-07 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_youtube_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csv_imports/')),
                ('property_type_name', models.CharField(default='Residential', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('packages_created', models.IntegerField(default=0)),
                ('packages_updated', models.IntegerField(default=0)),
                ('packages_skipped', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSV Import',
                'verbose_name_plural': 'CSV Imports',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
