# Generated by Django 5.2.8 on 2025-12-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_csvimport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvimport',
            name='property_type_name',
        ),
        migrations.AddField(
            model_name='csvimport',
            name='property_types_detected',
            field=models.CharField(blank=True, help_text='Auto-detected property types', max_length=500),
        ),
    ]
