# Generated by Django 5.2.8 on 2025-12-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_csvimport_property_type_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='details',
            field=models.TextField(blank=True, help_text='Detailed information, specifications, benefits - shown on category detail pages'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='details',
            field=models.TextField(blank=True, help_text='Detailed information, specifications, benefits - shown on subcategory pages'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description shown in catalog listings'),
        ),
        migrations.AlterField(
            model_name='package',
            name='installation_phase',
            field=models.CharField(choices=[('framing', 'Framing'), ('rough_ins', 'Rough-Ins'), ('insulation_drywall', 'Insulation and Drywall'), ('trim_finishes', 'Trim and Finishes')], default='rough_ins', help_text='Construction phase when this package is installed', max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description shown in catalog listings'),
        ),
    ]
