# Generated by Django 5.2.8 on 2025-12-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_details_subcategory_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='builder_section',
            field=models.CharField(blank=True, choices=[('network_automation', 'Network & Automation'), ('security', 'Security'), ('audio', 'Audio'), ('entertainment', 'Entertainment')], help_text='Section to display in builder showroom (e.g., Network & Automation, Security, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_catalog',
            field=models.BooleanField(default=True, help_text='Show this category in the regular catalog (uncheck for builder-only items)'),
        ),
    ]
