# Generated by Django 5.2.8 on 2025-12-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_builder_section_category_show_in_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video file directly (MP4, MOV, etc.). If both video and YouTube URL are provided, uploaded video takes priority.', null=True, upload_to='categories/videos/'),
        ),
    ]
