# Generated by Django 5.2.8 on 2025-12-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='builder_section',
            field=models.CharField(blank=True, choices=[('pre_wire', 'Pre-Wire'), ('automations', 'Automations'), ('entertainment_audio', 'Entertainment & Audio'), ('custom_solutions', 'Custom Solutions')], help_text='Section to display in builder showroom (e.g., Network & Automation, Security, etc.)', max_length=50),
        ),
    ]
