# Generated by Django 5.2.8 on 2026-01-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_package_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='catalog_only',
            field=models.BooleanField(default=False, help_text='If checked, package only shows in catalog - not in builder showroom'),
        ),
    ]
