# Generated by Django 5.2.8 on 2026-02-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_package_catalog_only'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVImport',
        ),
    ]
