# Generated by Django 5.2.8 on 2026-02-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_delete_csvimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='installation_phase',
            field=models.CharField(choices=[('framing', 'Framing'), ('rough_ins', 'Rough-Ins'), ('insulation_drywall', 'Insulation and Drywall'), ('trim_finishes', 'Trim and Finishes'), ('finished_property', 'Finished Property')], default='rough_ins', help_text='Construction phase when this package is installed', max_length=50),
        ),
    ]
