# Generated by Django 5.2.8 on 2026-02-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_categoryimage_categoryvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID or https://youtu.be/VIDEO_ID)', max_length=500),
        ),
        migrations.AlterField(
            model_name='categoryvideo',
            name='youtube_url',
            field=models.URLField(help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)', max_length=500),
        ),
    ]
