# Generated by Django 5.2.8 on 2026-02-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_category_youtube_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='catalog_only',
        ),
        migrations.AddField(
            model_name='package',
            name='visibility',
            field=models.CharField(choices=[('both', 'Both'), ('catalog', 'Catalog Only'), ('showroom', 'Showroom Only')], default='both', help_text='Where this package appears: catalog, builder showroom, or both', max_length=20),
        ),
    ]
