# Generated by Django 5.2.8 on 2025-12-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='address',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='city',
            field=models.CharField(default='', help_text='City', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='street',
            field=models.CharField(default='', help_text='Street address', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
