# Generated by Django 5.2.8 on 2025-12-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_remove_quoterequest_address_quoterequest_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='state',
            field=models.CharField(default='', help_text='State (2-letter abbreviation)', max_length=2),
            preserve_default=False,
        ),
    ]
