# Generated by Django 5.2.8 on 2025-12-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quoterequest_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='state',
            field=models.CharField(blank=True, help_text='State (2-letter abbreviation)', max_length=2),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='street',
            field=models.CharField(blank=True, help_text='Street address', max_length=300),
        ),
    ]
