# Generated by Django 5.2.8 on 2025-12-03 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_quoterequest_state_alter_quoterequest_street'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin team (not visible to customer)'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='final_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final quoted price (overrides estimated total when set)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='When the quote was finalized and sent to customer', null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='finalized_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who finalized this quote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quoterequestitem',
            name='price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit (leave blank for custom pricing)', max_digits=10, null=True),
        ),
    ]
