# Generated by Django 5.2.8 on 2025-12-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quoterequest_admin_notes_quoterequest_final_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequestitem',
            name='installation_phase_snapshot',
            field=models.CharField(blank=True, help_text='Installation phase at time of quote', max_length=50),
        ),
    ]
