# Generated by Django 5.2.8 on 2025-12-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_quoterequestitem_installation_phase_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='additional_emails',
            field=models.TextField(blank=True, help_text='Additional email addresses to send finalized quote to (one per line or comma-separated)', verbose_name='Additional Email Recipients'),
        ),
        migrations.AlterField(
            model_name='quoterequestitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes from the customer about this package (visible to customer in emails/PDFs)', verbose_name='Customer Notes'),
        ),
    ]
