# Generated by Django 5.2.8 on 2025-12-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_quoterequest_additional_emails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='additional_emails',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='email_recipients',
            field=models.TextField(blank=True, help_text='Email addresses to send finalized quote to (one per line or comma-separated). Defaults to customer email.', verbose_name='Email Recipients'),
        ),
    ]
