# Generated by Django 5.2.8 on 2025-12-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_remove_quoterequest_additional_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='builder_email',
            field=models.EmailField(blank=True, help_text='Email of the builder account to assign to the property created from this quote', max_length=254, verbose_name='Builder Email'),
        ),
    ]
