# Generated by Django 5.2.8 on 2025-12-31 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_quoterequest_builder_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Coupon code (case-insensitive)', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='Internal description of this coupon', max_length=200)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g., 10 for 10%) or fixed amount (e.g., 100.00)', max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used (leave blank for unlimited)', null=True)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order amount required (e.g., 5000.00)', max_digits=10, null=True)),
                ('max_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum order amount allowed (e.g., 25000.00)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Applied coupon code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='quotes.coupon'),
        ),
    ]
