# Generated by Django 5.2.8 on 2026-02-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_coupon_cart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequestitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin use only (not visible to customers)', verbose_name='Internal Notes'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='business_name',
            field=models.CharField(default='Listen Hear!', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='customer_email_subject',
            field=models.CharField(default='Your Listen Hear! Quote Request', max_length=200),
        ),
    ]
