# Generated by Django 5.2.8 on 2026-02-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_alter_quoterequestitem_notes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteConfiguration',
        ),
    ]
