# Generated by Django 5.2.8 on 2026-03-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_delete_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit at time of adding to cart (includes builder markup if applicable)', max_digits=10, null=True),
        ),
    ]
