# Generated by Django 5.1.4 on 2026-01-12 18:57

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload gallery image (any size, will auto-fit in masonry grid)', upload_to='gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='SEO: Describe the image for search engines and accessibility', max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Optional caption or description for marketing')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual ordering (0 = use upload date)')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Tags: living room, lighting, outdoor, theater, pool, etc.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
