#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput

exec gunicorn config.wsgi \
  --bind 0.0.0.0:5000 \
  --chdir=/app \
  --workers 2 \
  --timeout 60 \
  --max-requests 1000 \
  --max-requests-jitter 50
