# Generated by Django 5.2.8 on 2025-11-30 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_remove_propertynote_property_and_more'),
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Property name or identifier', max_length=200)),
                ('address', models.TextField(help_text='Full property address')),
                ('property_type', models.CharField(blank=True, help_text='e.g., Residential, Commercial', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('builders', models.ManyToManyField(help_text='Builders assigned to manage this property', limit_choices_to={'is_builder': True}, related_name='managed_properties', to=settings.AUTH_USER_MODEL)),
                ('quote_request', models.ForeignKey(blank=True, help_text='Original quote request that created this property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='quotes.quoterequest')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('package_description', models.TextField(blank=True)),
                ('price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('date_requested', 'Date Requested'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_install_date', models.DateField(blank=True, null=True)),
                ('confirmed_install_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('builder_notes', models.TextField(blank=True, help_text='Notes from builder')),
                ('company_notes', models.TextField(blank=True, help_text='Notes from company')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.package')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='builders.property')),
            ],
            options={
                'verbose_name': 'Purchased Package',
                'verbose_name_plural': 'Purchased Packages',
                'ordering': ['status', 'requested_install_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('general', 'General Note'), ('date_request', 'Date Request'), ('date_confirmation', 'Date Confirmation'), ('date_denial', 'Date Denial'), ('status_change', 'Status Change')], max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='builders.property')),
                ('package', models.ForeignKey(blank=True, help_text='Associated package if note is package-specific', null=True, on_delete=django.db.models.deletion.CASCADE, to='builders.purchasedpackage')),
            ],
            options={
                'verbose_name': 'Property Note',
                'verbose_name_plural': 'Property Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
