# Generated by Django 5.2.8 on 2025-12-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedpackage',
            name='installation_phase_snapshot',
            field=models.CharField(blank=True, help_text='Installation phase at time of purchase', max_length=50),
        ),
    ]
