# Generated by Django 5.2.8 on 2026-01-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0002_purchasedpackage_installation_phase_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedpackage',
            name='alternate_install_dates',
            field=models.JSONField(blank=True, default=list, help_text='List of alternate dates in ISO format (YYYY-MM-DD)'),
        ),
        migrations.AddField(
            model_name='purchasedpackage',
            name='category_snapshot',
            field=models.CharField(blank=True, help_text='Category name at time of purchase', max_length=200),
        ),
        migrations.AddField(
            model_name='purchasedpackage',
            name='confirmed_install_end_date',
            field=models.DateField(blank=True, help_text='End date if installation spans multiple days', null=True),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='confirmed_install_date',
            field=models.DateField(blank=True, help_text='Start date of confirmed installation', null=True),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='requested_install_date',
            field=models.DateField(blank=True, help_text='Primary requested date', null=True),
        ),
    ]
