# Generated by Django 5.2.8 on 2026-01-15 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0003_purchasedpackage_alternate_install_dates_and_more'),
        ('quotes', '0010_coupon_cart_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedpackage',
            options={'ordering': ['installation_phase_snapshot', 'package_name'], 'verbose_name': 'Purchased Package', 'verbose_name_plural': 'Purchased Packages'},
        ),
        migrations.RemoveField(
            model_name='propertynote',
            name='package',
        ),
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='alternate_install_dates',
        ),
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='builder_notes',
        ),
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='company_notes',
        ),
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='confirmed_install_date',
        ),
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='confirmed_install_end_date',
        ),
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='requested_install_date',
        ),
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='status',
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='builders',
            field=models.ManyToManyField(limit_choices_to={'is_builder': True}, related_name='managed_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='quote_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='quotes.quoterequest'),
        ),
        migrations.AlterField(
            model_name='propertynote',
            name='note_type',
            field=models.CharField(choices=[('general', 'General'), ('date_request', 'Date Request'), ('date_confirmation', 'Date Confirmed'), ('status_change', 'Status Change')], max_length=30),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='category_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='installation_phase_snapshot',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='PhaseInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('framing', 'Framing'), ('rough_ins', 'Rough-Ins'), ('insulation_drywall', 'Insulation & Drywall'), ('trim_finishes', 'Trim & Finishes')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('requested', 'Date Requested'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('alternate_dates', models.JSONField(blank=True, default=list)),
                ('builder_notes', models.TextField(blank=True)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('estimated_end_date', models.DateField(blank=True, null=True)),
                ('company_notes', models.TextField(blank=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_installations', to='builders.property')),
            ],
            options={
                'verbose_name': 'Phase Installation',
                'verbose_name_plural': 'Phase Installations',
                'ordering': ['phase'],
                'unique_together': {('property', 'phase')},
            },
        ),
        migrations.AddField(
            model_name='propertynote',
            name='phase_installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builders.phaseinstallation'),
        ),
    ]
