# Generated by Django 5.2.8 on 2026-02-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builders', '0004_alter_purchasedpackage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phaseinstallation',
            options={'ordering': ['phase'], 'verbose_name': 'Installation', 'verbose_name_plural': 'Installations'},
        ),
        migrations.AlterField(
            model_name='phaseinstallation',
            name='phase',
            field=models.CharField(choices=[('framing', 'Framing'), ('rough_ins', 'Rough-Ins'), ('insulation_drywall', 'Insulation & Drywall'), ('trim_finishes', 'Trim & Finishes'), ('finished_property', 'Finished Property')], max_length=50),
        ),
    ]
