# Generated by Django 5.2.8 on 2025-12-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Listen Hear Smart Homes', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('monday_hours', models.CharField(default='9:00 AM - 5:00 PM', max_length=50)),
                ('tuesday_hours', models.CharField(default='9:00 AM - 5:00 PM', max_length=50)),
                ('wednesday_hours', models.CharField(default='9:00 AM - 5:00 PM', max_length=50)),
                ('thursday_hours', models.CharField(default='9:00 AM - 5:00 PM', max_length=50)),
                ('friday_hours', models.CharField(default='9:00 AM - 5:00 PM', max_length=50)),
                ('saturday_hours', models.CharField(default='Closed', max_length=50)),
                ('sunday_hours', models.CharField(default='Closed', max_length=50)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Business Information',
                'verbose_name_plural': 'Business Information',
            },
        ),
    ]
