# Generated by Django 5.2.8 on 2025-12-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='google_maps_embed_url',
            field=models.TextField(blank=True, help_text='Full Google Maps embed URL from maps.google.com (Share > Embed a map)'),
        ),
    ]
