# Generated by Django 5.2.8 on 2026-01-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='preferred_date',
            field=models.DateField(blank=True, null=True, verbose_name='Preferred date(s)'),
        ),
    ]
