# Generated by Django 5.2.8 on 2026-02-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_servicerequest_preferred_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Listen Hear Smart Homes', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('monday_hours', models.CharField(default='9:00 AM - 5:00 PM', max_length=50)),
                ('tuesday_hours', models.CharField(default='9:00 AM - 5:00 PM', max_length=50)),
                ('wednesday_hours', models.CharField(default='9:00 AM - 5:00 PM', max_length=50)),
                ('thursday_hours', models.CharField(default='9:00 AM - 5:00 PM', max_length=50)),
                ('friday_hours', models.CharField(default='9:00 AM - 5:00 PM', max_length=50)),
                ('saturday_hours', models.CharField(default='Closed', max_length=50)),
                ('sunday_hours', models.CharField(default='Closed', max_length=50)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('notification_emails', models.JSONField(default=list, help_text='List of email addresses to receive quote notifications')),
                ('customer_email_subject', models.CharField(default='Your Listen Hear! Quote Request', max_length=200)),
                ('customer_email_message', models.TextField(default="Thank you for your quote request. We'll review your requirements and get back to you within 1-2 business days.")),
                ('quote_disclaimer', models.TextField(blank=True, default='This is an estimate based on the packages selected. Final pricing will be determined after consultation and site evaluation.')),
                ('google_maps_embed_url', models.TextField(blank=True, help_text='Full Google Maps embed URL from maps.google.com (Share > Embed a map)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.DeleteModel(
            name='BusinessInfo',
        ),
    ]
