# Generated by Django 5.2.8 on 2026-02-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfiguration_delete_businessinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text='Job title or role', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Short blurb about this team member')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Upload an MP4 video for the hero background loop', null=True, upload_to='site/video/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='Or provide an external URL to a video file (used if no upload)'),
        ),
    ]
