# Generated by Django 5.2.8 on 2026-02-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teammember_siteconfiguration_hero_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(help_text='Brand logo image', upload_to='brands/')),
                ('website_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Brand Partner',
                'verbose_name_plural': 'Brand Partners',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
